import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Theme } from '@radix-ui/themes';
import { Suspense } from 'react';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import NavBar from './NavBar';
import Footer from './Footer';
import AuthProvider from './AuthProvider';
import '@radix-ui/themes/styles.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Theme
          appearance="light"
          accentColor="indigo"
          className="flex flex-col h-screen justify-between"
        >
          <AuthProvider>
            <Suspense>
              <div>
                <ToastContainer />
                <NavBar />
                <main>{children}</main>
              </div>
              <Footer />
            </Suspense>
          </AuthProvider>
        </Theme>
      </body>
    </html>
  );
}
